// Code generated by MockGen. DO NOT EDIT.
// Source: linkshortener/internal/database (interfaces: SQL)

// Package database is a generated GoMock package.
package database

import (
	context "context"
	types "linkshortener/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSQL is a mock of SQL interface.
type MockSQL struct {
	ctrl     *gomock.Controller
	recorder *MockSQLMockRecorder
}

// MockSQLMockRecorder is the mock recorder for MockSQL.
type MockSQLMockRecorder struct {
	mock *MockSQL
}

// NewMockSQL creates a new mock instance.
func NewMockSQL(ctrl *gomock.Controller) *MockSQL {
	mock := &MockSQL{ctrl: ctrl}
	mock.recorder = &MockSQLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQL) EXPECT() *MockSQLMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSQL) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSQLMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSQL)(nil).Close))
}

// CreateLink mocks base method.
func (m *MockSQL) CreateLink(arg0 context.Context, arg1 int64, arg2 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockSQLMockRecorder) CreateLink(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockSQL)(nil).CreateLink), arg0, arg1, arg2)
}

// CreateUser mocks base method.
func (m *MockSQL) CreateUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockSQLMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockSQL)(nil).CreateUser), arg0, arg1)
}

// DeleteAllLinksByUser mocks base method.
func (m *MockSQL) DeleteAllLinksByUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllLinksByUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllLinksByUser indicates an expected call of DeleteAllLinksByUser.
func (mr *MockSQLMockRecorder) DeleteAllLinksByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllLinksByUser", reflect.TypeOf((*MockSQL)(nil).DeleteAllLinksByUser), arg0, arg1)
}

// DeleteLinkByCode mocks base method.
func (m *MockSQL) DeleteLinkByCode(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLinkByCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLinkByCode indicates an expected call of DeleteLinkByCode.
func (mr *MockSQLMockRecorder) DeleteLinkByCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinkByCode", reflect.TypeOf((*MockSQL)(nil).DeleteLinkByCode), arg0, arg1, arg2)
}

// DeleteLinkById mocks base method.
func (m *MockSQL) DeleteLinkById(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLinkById", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLinkById indicates an expected call of DeleteLinkById.
func (mr *MockSQLMockRecorder) DeleteLinkById(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinkById", reflect.TypeOf((*MockSQL)(nil).DeleteLinkById), arg0, arg1, arg2)
}

// GetAllLinksByUser mocks base method.
func (m *MockSQL) GetAllLinksByUser(arg0 context.Context, arg1 int64) ([]types.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinksByUser", arg0, arg1)
	ret0, _ := ret[0].([]types.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinksByUser indicates an expected call of GetAllLinksByUser.
func (mr *MockSQLMockRecorder) GetAllLinksByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinksByUser", reflect.TypeOf((*MockSQL)(nil).GetAllLinksByUser), arg0, arg1)
}

// GetLink mocks base method.
func (m *MockSQL) GetLink(arg0 context.Context, arg1 string) (*types.LinkCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", arg0, arg1)
	ret0, _ := ret[0].(*types.LinkCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockSQLMockRecorder) GetLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockSQL)(nil).GetLink), arg0, arg1)
}

// GetUserIDByTelegramID mocks base method.
func (m *MockSQL) GetUserIDByTelegramID(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByTelegramID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByTelegramID indicates an expected call of GetUserIDByTelegramID.
func (mr *MockSQLMockRecorder) GetUserIDByTelegramID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByTelegramID", reflect.TypeOf((*MockSQL)(nil).GetUserIDByTelegramID), arg0, arg1)
}

// SetShortCode mocks base method.
func (m *MockSQL) SetShortCode(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShortCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetShortCode indicates an expected call of SetShortCode.
func (mr *MockSQLMockRecorder) SetShortCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShortCode", reflect.TypeOf((*MockSQL)(nil).SetShortCode), arg0, arg1, arg2)
}

// UpdateLink mocks base method.
func (m *MockSQL) UpdateLink(arg0 context.Context, arg1 int64, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockSQLMockRecorder) UpdateLink(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockSQL)(nil).UpdateLink), arg0, arg1, arg2, arg3)
}
