// Code generated by MockGen. DO NOT EDIT.
// Source: linkshortener/internal/database (interfaces: Analytics)

// Package database is a generated GoMock package.
package database

import (
	context "context"
	types "linkshortener/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAnalytics is a mock of Analytics interface.
type MockAnalytics struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsMockRecorder
}

// MockAnalyticsMockRecorder is the mock recorder for MockAnalytics.
type MockAnalyticsMockRecorder struct {
	mock *MockAnalytics
}

// NewMockAnalytics creates a new mock instance.
func NewMockAnalytics(ctrl *gomock.Controller) *MockAnalytics {
	mock := &MockAnalytics{ctrl: ctrl}
	mock.recorder = &MockAnalyticsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalytics) EXPECT() *MockAnalyticsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAnalytics) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAnalyticsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAnalytics)(nil).Close))
}

// GetAllAnalytic mocks base method.
func (m *MockAnalytics) GetAllAnalytic(arg0 context.Context, arg1 int64) ([]types.Analytic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAnalytic", arg0, arg1)
	ret0, _ := ret[0].([]types.Analytic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAnalytic indicates an expected call of GetAllAnalytic.
func (mr *MockAnalyticsMockRecorder) GetAllAnalytic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAnalytic", reflect.TypeOf((*MockAnalytics)(nil).GetAllAnalytic), arg0, arg1)
}

// GetAnalyticByCode mocks base method.
func (m *MockAnalytics) GetAnalyticByCode(arg0 context.Context, arg1 string, arg2 int64) ([]types.Analytic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyticByCode", arg0, arg1, arg2)
	ret0, _ := ret[0].([]types.Analytic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalyticByCode indicates an expected call of GetAnalyticByCode.
func (mr *MockAnalyticsMockRecorder) GetAnalyticByCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyticByCode", reflect.TypeOf((*MockAnalytics)(nil).GetAnalyticByCode), arg0, arg1, arg2)
}

// PushClick mocks base method.
func (m *MockAnalytics) PushClick(arg0 types.ClickData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushClick", arg0)
}

// PushClick indicates an expected call of PushClick.
func (mr *MockAnalyticsMockRecorder) PushClick(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushClick", reflect.TypeOf((*MockAnalytics)(nil).PushClick), arg0)
}

// Start mocks base method.
func (m *MockAnalytics) Start(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", arg0)
}

// Start indicates an expected call of Start.
func (mr *MockAnalyticsMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAnalytics)(nil).Start), arg0)
}
