// Code generated by MockGen. DO NOT EDIT.
// Source: linkshortener/internal/database (interfaces: LinksRepo)

// Package database is a generated GoMock package.
package database

import (
	context "context"
	types "linkshortener/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLinksRepo is a mock of LinksRepo interface.
type MockLinksRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLinksRepoMockRecorder
}

// MockLinksRepoMockRecorder is the mock recorder for MockLinksRepo.
type MockLinksRepoMockRecorder struct {
	mock *MockLinksRepo
}

// NewMockLinksRepo creates a new mock instance.
func NewMockLinksRepo(ctrl *gomock.Controller) *MockLinksRepo {
	mock := &MockLinksRepo{ctrl: ctrl}
	mock.recorder = &MockLinksRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinksRepo) EXPECT() *MockLinksRepoMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockLinksRepo) CreateLink(arg0 context.Context, arg1 int64, arg2 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinksRepoMockRecorder) CreateLink(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLinksRepo)(nil).CreateLink), arg0, arg1, arg2)
}

// DeleteAllLinksByUser mocks base method.
func (m *MockLinksRepo) DeleteAllLinksByUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllLinksByUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllLinksByUser indicates an expected call of DeleteAllLinksByUser.
func (mr *MockLinksRepoMockRecorder) DeleteAllLinksByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllLinksByUser", reflect.TypeOf((*MockLinksRepo)(nil).DeleteAllLinksByUser), arg0, arg1)
}

// DeleteLinkByCode mocks base method.
func (m *MockLinksRepo) DeleteLinkByCode(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLinkByCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLinkByCode indicates an expected call of DeleteLinkByCode.
func (mr *MockLinksRepoMockRecorder) DeleteLinkByCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinkByCode", reflect.TypeOf((*MockLinksRepo)(nil).DeleteLinkByCode), arg0, arg1, arg2)
}

// DeleteLinkById mocks base method.
func (m *MockLinksRepo) DeleteLinkById(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLinkById", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLinkById indicates an expected call of DeleteLinkById.
func (mr *MockLinksRepoMockRecorder) DeleteLinkById(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinkById", reflect.TypeOf((*MockLinksRepo)(nil).DeleteLinkById), arg0, arg1, arg2)
}

// GetAllLinksByUser mocks base method.
func (m *MockLinksRepo) GetAllLinksByUser(arg0 context.Context, arg1 int64) ([]types.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinksByUser", arg0, arg1)
	ret0, _ := ret[0].([]types.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinksByUser indicates an expected call of GetAllLinksByUser.
func (mr *MockLinksRepoMockRecorder) GetAllLinksByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinksByUser", reflect.TypeOf((*MockLinksRepo)(nil).GetAllLinksByUser), arg0, arg1)
}

// GetLink mocks base method.
func (m *MockLinksRepo) GetLink(arg0 context.Context, arg1 string) (*types.LinkCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", arg0, arg1)
	ret0, _ := ret[0].(*types.LinkCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockLinksRepoMockRecorder) GetLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockLinksRepo)(nil).GetLink), arg0, arg1)
}

// SetShortCode mocks base method.
func (m *MockLinksRepo) SetShortCode(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShortCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetShortCode indicates an expected call of SetShortCode.
func (mr *MockLinksRepoMockRecorder) SetShortCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShortCode", reflect.TypeOf((*MockLinksRepo)(nil).SetShortCode), arg0, arg1, arg2)
}

// UpdateLink mocks base method.
func (m *MockLinksRepo) UpdateLink(arg0 context.Context, arg1 int64, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockLinksRepoMockRecorder) UpdateLink(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockLinksRepo)(nil).UpdateLink), arg0, arg1, arg2, arg3)
}
