// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	types "linkshortener/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServerDB is a mock of ServerDB interface.
type MockServerDB struct {
	ctrl     *gomock.Controller
	recorder *MockServerDBMockRecorder
}

// MockServerDBMockRecorder is the mock recorder for MockServerDB.
type MockServerDBMockRecorder struct {
	mock *MockServerDB
}

// NewMockServerDB creates a new mock instance.
func NewMockServerDB(ctrl *gomock.Controller) *MockServerDB {
	mock := &MockServerDB{ctrl: ctrl}
	mock.recorder = &MockServerDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerDB) EXPECT() *MockServerDBMockRecorder {
	return m.recorder
}

// GetLinkCacheByCode mocks base method.
func (m *MockServerDB) GetLinkCacheByCode(ctx context.Context, shortCode string) (*types.LinkCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkCacheByCode", ctx, shortCode)
	ret0, _ := ret[0].(*types.LinkCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkCacheByCode indicates an expected call of GetLinkCacheByCode.
func (mr *MockServerDBMockRecorder) GetLinkCacheByCode(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkCacheByCode", reflect.TypeOf((*MockServerDB)(nil).GetLinkCacheByCode), ctx, shortCode)
}

// PushClick mocks base method.
func (m *MockServerDB) PushClick(data types.ClickData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushClick", data)
}

// PushClick indicates an expected call of PushClick.
func (mr *MockServerDBMockRecorder) PushClick(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushClick", reflect.TypeOf((*MockServerDB)(nil).PushClick), data)
}
