// Code generated by MockGen. DO NOT EDIT.
// Source: shortener.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	types "linkshortener/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortenerDB is a mock of ShortenerDB interface.
type MockShortenerDB struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerDBMockRecorder
}

// MockShortenerDBMockRecorder is the mock recorder for MockShortenerDB.
type MockShortenerDBMockRecorder struct {
	mock *MockShortenerDB
}

// NewMockShortenerDB creates a new mock instance.
func NewMockShortenerDB(ctrl *gomock.Controller) *MockShortenerDB {
	mock := &MockShortenerDB{ctrl: ctrl}
	mock.recorder = &MockShortenerDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerDB) EXPECT() *MockShortenerDBMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockShortenerDB) CreateLink(ctx context.Context, userID int64, originalLink string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, userID, originalLink)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockShortenerDBMockRecorder) CreateLink(ctx, userID, originalLink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockShortenerDB)(nil).CreateLink), ctx, userID, originalLink)
}

// DeleteLinkById mocks base method.
func (m *MockShortenerDB) DeleteLinkById(ctx context.Context, userId, linkId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLinkById", ctx, userId, linkId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLinkById indicates an expected call of DeleteLinkById.
func (mr *MockShortenerDBMockRecorder) DeleteLinkById(ctx, userId, linkId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinkById", reflect.TypeOf((*MockShortenerDB)(nil).DeleteLinkById), ctx, userId, linkId)
}

// GetLinkCacheByCode mocks base method.
func (m *MockShortenerDB) GetLinkCacheByCode(ctx context.Context, shortCode string) (*types.LinkCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkCacheByCode", ctx, shortCode)
	ret0, _ := ret[0].(*types.LinkCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkCacheByCode indicates an expected call of GetLinkCacheByCode.
func (mr *MockShortenerDBMockRecorder) GetLinkCacheByCode(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkCacheByCode", reflect.TypeOf((*MockShortenerDB)(nil).GetLinkCacheByCode), ctx, shortCode)
}

// SetShortCode mocks base method.
func (m *MockShortenerDB) SetShortCode(ctx context.Context, id int64, shortCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShortCode", ctx, id, shortCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetShortCode indicates an expected call of SetShortCode.
func (mr *MockShortenerDBMockRecorder) SetShortCode(ctx, id, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShortCode", reflect.TypeOf((*MockShortenerDB)(nil).SetShortCode), ctx, id, shortCode)
}
