// Code generated by MockGen. DO NOT EDIT.
// Source: linkshortener/internal/bot (interfaces: Shortener)

// Package bot is a generated GoMock package.
package bot

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortener is a mock of Shortener interface.
type MockShortener struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerMockRecorder
}

// MockShortenerMockRecorder is the mock recorder for MockShortener.
type MockShortenerMockRecorder struct {
	mock *MockShortener
}

// NewMockShortener creates a new mock instance.
func NewMockShortener(ctrl *gomock.Controller) *MockShortener {
	mock := &MockShortener{ctrl: ctrl}
	mock.recorder = &MockShortenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortener) EXPECT() *MockShortenerMockRecorder {
	return m.recorder
}

// CreateNewCustomShortLink mocks base method.
func (m *MockShortener) CreateNewCustomShortLink(arg0 context.Context, arg1, arg2 string, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewCustomShortLink", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewCustomShortLink indicates an expected call of CreateNewCustomShortLink.
func (mr *MockShortenerMockRecorder) CreateNewCustomShortLink(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewCustomShortLink", reflect.TypeOf((*MockShortener)(nil).CreateNewCustomShortLink), arg0, arg1, arg2, arg3)
}

// CreateNewShortLink mocks base method.
func (m *MockShortener) CreateNewShortLink(arg0 context.Context, arg1 string, arg2 int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewShortLink", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewShortLink indicates an expected call of CreateNewShortLink.
func (mr *MockShortenerMockRecorder) CreateNewShortLink(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewShortLink", reflect.TypeOf((*MockShortener)(nil).CreateNewShortLink), arg0, arg1, arg2)
}

// IsValidShortCode mocks base method.
func (m *MockShortener) IsValidShortCode(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidShortCode", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidShortCode indicates an expected call of IsValidShortCode.
func (mr *MockShortenerMockRecorder) IsValidShortCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidShortCode", reflect.TypeOf((*MockShortener)(nil).IsValidShortCode), arg0)
}
