// Code generated by MockGen. DO NOT EDIT.
// Source: linkshortener/internal/bot (interfaces: Database)

// Package bot is a generated GoMock package.
package bot

import (
	context "context"
	types "linkshortener/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockDatabase) CreateUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDatabaseMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDatabase)(nil).CreateUser), arg0, arg1)
}

// DeleteLinkByCode mocks base method.
func (m *MockDatabase) DeleteLinkByCode(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLinkByCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLinkByCode indicates an expected call of DeleteLinkByCode.
func (mr *MockDatabaseMockRecorder) DeleteLinkByCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinkByCode", reflect.TypeOf((*MockDatabase)(nil).DeleteLinkByCode), arg0, arg1, arg2)
}

// GetAllAnalytic mocks base method.
func (m *MockDatabase) GetAllAnalytic(arg0 context.Context, arg1 int64) ([]types.Analytic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAnalytic", arg0, arg1)
	ret0, _ := ret[0].([]types.Analytic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAnalytic indicates an expected call of GetAllAnalytic.
func (mr *MockDatabaseMockRecorder) GetAllAnalytic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAnalytic", reflect.TypeOf((*MockDatabase)(nil).GetAllAnalytic), arg0, arg1)
}

// GetAllLinksByUser mocks base method.
func (m *MockDatabase) GetAllLinksByUser(arg0 context.Context, arg1 int64) ([]types.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinksByUser", arg0, arg1)
	ret0, _ := ret[0].([]types.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinksByUser indicates an expected call of GetAllLinksByUser.
func (mr *MockDatabaseMockRecorder) GetAllLinksByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinksByUser", reflect.TypeOf((*MockDatabase)(nil).GetAllLinksByUser), arg0, arg1)
}

// GetAnalyticByCode mocks base method.
func (m *MockDatabase) GetAnalyticByCode(arg0 context.Context, arg1 string, arg2 int64) ([]types.Analytic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyticByCode", arg0, arg1, arg2)
	ret0, _ := ret[0].([]types.Analytic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalyticByCode indicates an expected call of GetAnalyticByCode.
func (mr *MockDatabaseMockRecorder) GetAnalyticByCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyticByCode", reflect.TypeOf((*MockDatabase)(nil).GetAnalyticByCode), arg0, arg1, arg2)
}

// GetUserIDByTelegramID mocks base method.
func (m *MockDatabase) GetUserIDByTelegramID(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByTelegramID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByTelegramID indicates an expected call of GetUserIDByTelegramID.
func (mr *MockDatabaseMockRecorder) GetUserIDByTelegramID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByTelegramID", reflect.TypeOf((*MockDatabase)(nil).GetUserIDByTelegramID), arg0, arg1)
}

// UpdateLink mocks base method.
func (m *MockDatabase) UpdateLink(arg0 context.Context, arg1 int64, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockDatabaseMockRecorder) UpdateLink(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockDatabase)(nil).UpdateLink), arg0, arg1, arg2, arg3)
}
